# Iteration in 1-D NumPy Array

In [30]:
#  Iterate on the elements of the following 1-D array
#Iteration(we go through element one by one) generally mean looping like for we use for loop

In [31]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


# Iteration in 2-D NumPy Array

In [32]:
# Iterating 2_D Arrays : In a 2D array it will gothrough all the rows
# Iterate on the elements of the following 2_D arrays


In [33]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [34]:
# iterate on a N_D array  it will go through n-1th dimension one by one....
# to return actual value the scalars ,we have to iterate the arrays in each dimension

In [35]:
# if we want to print the scalar value which are present in those directions
# Iterate on each scalar element of the 2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr: # first loop represent dimensions
    for y in x: # second loop represent element which present at dimension, then we are printing that element i.e scalarvalue
        print(y)

1
2
3
4
5
6


# Iteration in 3D NumPy Array

In [36]:
# In a 3D array it will go through all the 2D arrays
# Iterate on element of the following 3D arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3D Nmppy Array
for x in arr: # with help of for loop it will go through all the 2D arrays
    print(x) 
# result is 2D


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [37]:
# return the actual values,scalars, we have to iterate the arrays in each dimension
# we have to iterate the arrays in each dimensions
# iterate down to the scalars
# we ue 3 loops because we are working on 3D arrays
# Nested loops
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3D Nmppy Array
for x in arr: # outer dimension ,3-D represent
    for y in x: # inside of the outer dimension , 2-D represent 
        for z in y: # inside of the outer to the outer dimension , 1-D represent
            print(z) # printing values in dimensions
# it will print the scalars 

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating  Arrays using nditer( )

In [38]:
# We realized on previous code when dimension increases we have to use more and more foor loops so we have a builton func
# for 3D arrays we require 3 for loops
# for nD arrays we require n for loops so it is tideous
# we will use builton func nditer()

In [39]:
# no nested loop require here
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr): # arr as argument to this func
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array with Different Data Types

In [40]:
# if we have data type i.e integer float if we want to change it data type we use op_dtypes arguments
# Numpy doesnot change the data type of element in-place 
# it need some extra space to perform action ,that extra space called buffer
# in order to enable it nditer() we pass flags = ['buffered']

In [41]:
# Iterate through the array as string 
import numpy as np
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']): # ,flags = ['buffered'] we want to change datattype of 
                                                           # array element but we can't do here at same position
                                                           # op_dtype=['S'] it will convert into strings
     print(x)

b'1'
b'2'
b'3'


In [42]:
# iterate with different step size (with some slots we want to perform iteration and print values)
# Iterate through every scalar element of 2D array skipping (1 element)
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]]) # 2D array
for x in np.nditer(arr[:,::2]): # 2 reprent space of 2 mean step size of 1 , (: L.H.S represent that we need to take all rows
                                    #under consederation)
    print(x)
    

1
3
5
7


In [43]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]]) # 2D array
for x in np.nditer(arr[:,::3]): # print with space 3 and stepsize 2
    print(x)

1
4
5
8


In [44]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]]) # 2D array
for x in np.nditer(arr[:,::1]): # print all v alue with no stepsize
    print(x)

1
2
3
4
5
6
7
8


In [45]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]]) # 2D array
for x in np.nditer(arr[1:,::2]): # it will take 1row not 0row and print value with stepsize 1
    print(x)

5
7


# Enumerated Iteration using ndenumerate( )

In [46]:
# SOmetime we require corresponding index of the element  while iterating the ndnumerate() method
# can be used for those use cases

In [47]:
# Enumerate on following 1_D arrays Elements
import numpy as np
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr): # idx represent index value position for of every element in array perform
                                   # enumeration then print index value(position value) and element both
    print(idx,x) # idx represent index value position for

(0,) 1
(1,) 2
(2,) 3


In [48]:
# for 2D
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr): # idx represent index value position for of every element in array perform
                                    #  enumeration then print index value(position value) and element both       
              print(idx,x)             

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [49]:
# for 3D
import numpy as np
arr=np.array([[[1,2,3]]])
for idx,x in np.ndenumerate(arr): # idx represent index value position for of every element in array perform
                                    #  enumeration then print index value(position value) and element both       
              print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
