# Random Number in Numpy

In [22]:
#random number mean something which  cannot predict logically on behalf of logic this number is produce there are two
#types of random no,1 = pseudo and another is True random""""""


In [23]:
# Computer work on program and program is set of instruction and this instruction work on machines
# program written on basis of different algorithm
# program to generate a random number so there is algorithm behind that so there must be prediction
# algorithm=sequence of step=no of steps
# random number is predicted so why we called it as a random number 
# obviously random no made of a generator algorithms which is called as a pseudo random randomness
# Can we make truely random numbers
# yes in order to generate True random no we need to get some random data and it is collected by outer sources like mouse 
# moment,keystrokes etc
#randomness need in security

# Generate Random Number

In [24]:
# Generate a random integer from 0 to 100

In [25]:
import numpy as np
from numpy import random # we are importing a module from numpy package
x=random.randint(100) # from 0 to 100ick any random int
print(x) # we will get different number at every new time

10


#  Generate Random Float

In [26]:
# Generate a random float from 0 to 100
import numpy as numpy
from numpy import random
x=random.rand() # it will print any float between 0 to 1
print(x)


0.6237355350484476


# Generate Random Arrays

In [27]:
# Two methods
# integer :The randint() method takes a size "parameter" where we can specify shape of an array
# Float : The rand( )method also allows you to specify shape of the array

# For Integers

In [28]:
# Generate 1D array with 5 different elements all time

In [29]:
import numpy as np
from numpy import random 
x= random.randint(100,size=(5)) # from 0 to 100 we need to pick a random number and size=5 which mean we need to create 
                                # 1-D array with 5 elements
print(x) # it will print 1D array with 5 different element all times

[69 48 69 40 62]


In [30]:
#Generate a 2D array with 3 rows ,each row containing 5 random integer from 0 to 100

In [31]:
import numpy as np
from numpy import random 
x= random.randint(100,size=(3,5)) # from 0 to 100 we need to pick a random number and size=5 which mean we need to create 
                                # 2-D array with 5 elements and 3 rows
print(x) # it will print 2D array with 3 rows and each row contain 5 different random number

[[45  1 39 46 28]
 [17 23 13 84  7]
 [10 67 47 91 11]]


# For Floats

In [32]:
# Float : The rand( )method also allows you to specify shape of the array

In [33]:
# Generate a 1D array containing 5 random floats
import numpy as np
from numpy import random 
x= random.rand(5) # from 0 to 1 we need to pick a random  float number and size=5 which mean we need to create 
                                # 1-D array with 5 elements
print(x)

[0.6564726  0.71478834 0.1053716  0.58311662 0.27137629]


In [34]:
# Generate a 2D array with 3 rows , each row containing 5 random numbers
import numpy as np
from numpy import random 
x= random.rand(3,5) # from 0 to 1 we need to pick a random number and size=5 which mean we need to create 
                                # 2-D array with 5 elements and 3 rows
print(x) # (3,5) three rows and 5 different float no in each row will print

[[0.18603576 0.62552128 0.4579632  0.34949712 0.63244396]
 [0.98160467 0.56100226 0.56796485 0.65003334 0.57060785]
 [0.07845281 0.79988839 0.33302941 0.40674362 0.4058854 ]]


# Generate Random number from an Array

In [35]:
# we have Random array and we need to generate random number from given array
# There is a method choice() which allows to generate a random value based upon an array
#Choice() method take an array as a parameter and randomly return one of the value present in an array

In [36]:
# Return one of the values in an array
import numpy as np
from numpy import random
x= random.choice([3,5,7,9]) # !D array as parameter 
print(x) # out of 4 element it will print any one randomly

5


In [37]:
# The choice( method allows you to return an array of values . Add a size parameter to specify the shape of the array
import numpy as np
from numpy import random
x= random.choice([3,5,7,9],size=(3,5)) # 1D array as parameter our task to make 2D array with 3 rows and 5 
                                       # element in each row those element come from given 1D array  
print(x) # it will print all time random number from 1D array


[[3 7 3 3 3]
 [3 7 3 5 3]
 [5 7 3 5 9]]
