In [2]:
# Access element in an Array form

In [60]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[1])

1
2


In [61]:
#Access element and add them

In [62]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


# Accessing 2-D Array Elements

In [63]:
# This element present at 0 axis not and element present at 1 axis[0,0] bracket shows 0 axis at position 0

In [64]:
import numpy as np
arr = np.array([[1,2,3,4]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[0,0])

[[1 2 3 4]]
2
(1, 4)
1


In [65]:
# Since the above code exist on 0 axis if we try to find at 1 axis then we will get obviously an error

In [11]:
import numpy as np
arr = np.array([[1,2,3,4]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[1,0])
print(arr[0,3])

[[1 2 3 4]]
2
(1, 4)


IndexError: index 1 is out of bounds for axis 0 with size 1

In [13]:
# Two list as an arguments in 2 DImensions which mean we have 0axis and 1axis both

In [14]:
import numpy as np
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
arr=np.array([list1,list2])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[0,0])
print(arr[0,1])
print(arr[1,0])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
1
2
6


In [15]:
# we can use list as an index elements 1D array

In [22]:
import numpy as np
list1=[1,2,3,4,5]
arr=np.array(list1)
print(arr[[2,4]])
print(arr.ndim)

[3 5]
1


# Accessing 3Dimension Array Elements

In [25]:
# list as an arguments with three square brackets
#3 axis are present i.e 0-axis,1-axis,2-axis
# The above code has an element only on 0-axis not on 1-axis and 2-axis

In [26]:
import numpy as np
arr=np.array([[[1,2,3]]])
print(arr[0,0,2])# [0,0,2] here 0 represent outer 0 axis, 0 stand for 1-axis and 2 inner axis position


3


In [27]:
# above same code for 1 axis since 1-axis and 2-axis are absent so we will get an error

In [28]:
import numpy as np
arr=np.array([[[1,2,3]]])
print(arr[0,1,2])

IndexError: index 1 is out of bounds for axis 1 with size 1

In [30]:
#For 2 list as an arguments in an 3Dimensions array 

In [31]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(arr[0,1,0])#0axis is empty ,1 is second row of list and ,again 0 is index of second row

[[[1 2 3]
  [4 5 6]]]
4


In [34]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(arr[0,1,2])#0axis is empty ,1 is second row of list, and 2 is index of second row

[[[1 2 3]
  [4 5 6]]]
6


In [38]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(arr[0,0,2])#0axis is empty ,0 is first row of list, and 2 is index of first row

[[[1 2 3]
  [4 5 6]]]
3


In [42]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,1,2])# 1 represent outer axis again 1 represnt 2 row of outer matrix and 2 is the index of 2 row of outer matrix

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


# Negative Indexing(access array element from the end)

In [45]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[-1])# last element of the list


5


In [ ]:
# Its a 2D list because of 2 square brackets

In [46]:
import numpy as np
arr=np.array([[1,2,3,4,5]])# all elements present at only 0 axis,none of one on 1 axis
print(arr[0,-1])# 0 means the list array and -1 mean last element of list

5


In [47]:
import numpy as np
arr=np.array([[1,2,3,4,5]])# all elements present at only 0 axis,none of one on 1 axis
print(arr[0,-2])

4


In [48]:
import numpy as np
arr=np.array([[1,2,3,4,5]])# all elements present at only 0 axis,none of one on 1 axis
print(arr[1,-1])# it will show error because no element belong to 1 axis

IndexError: index 1 is out of bounds for axis 0 with size 1

In [51]:
# 2 lists as an arguments with 2D array so all element of 1 list represent 0 axis and all element of 2 list is 1axis

In [52]:
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,-1])# 1 is representing 1axis and again -1 represent last element of 1 axis

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


In [54]:
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0,-1])# 0 is representing 0axis and again -1 represent last element of 0 axis

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5


# Boolean Indexing

In [56]:
import numpy as np
list=[6,7,8,9,10]#for 1D array
arr=np.array(list)
print(arr)
print(arr>7)#element greater than 7 so print True else false

[ 6  7  8  9 10]
[False False  True  True  True]


In [58]:
import numpy as np
list=[6,7,8,9,10]
arr = np.array([list])
print(arr)
print(arr>7)#Printing boolean values here(only checking)
print(arr[arr>7])#argument again to the array(print true satisfy value to another array form)

[[ 6  7  8  9 10]]
[[False False  True  True  True]]
[ 8  9 10]


In [59]:
import numpy as np
nums=np.arange(20)# from 0 to 19 array inform of 1D
print(nums)
odd_num = nums[nums % 2==1] # if reminder =1 then correspond to that no print odd number
print(odd_num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
