In [1]:
list=[1,2,3,4,5]
arr=list[1:3]#3 is exclude
print(arr)

[2, 3]


In [2]:
#Code for Slicing Numpy which is similar to slicing list in python

In [3]:
import numpy as np
arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])# 2D array
print("The NumPy array is:")
print(arr)
arr1=arr[1:3,:3]#(row 1 to 3(3 is not include) and first 3 columns)(1:3, represent row,:3 it represent column(column 3 not include))
print("The Sliced Numpy Array is:")
print(arr1)

The NumPy array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The Sliced Numpy Array is:
[[4 5 6]
 [9 8 7]]


In [4]:
#Slice elements from index 1 to index 5 from the following array

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])# 5 is not include

[2 3 4 5]


In [6]:
#Slice elements from index 4 to the end of the array

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
#Slice elements from index 0 to 4

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# Negative Slicing:Use the minus operator to refer to an index from the end 

In [9]:
# Slice from index 3 from the end to index 1 from the end

In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


# Step:(Use the step value to determine the step of the slicing )

In [12]:
# Return every other element from index 1 to index 5 

In [15]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7]) # print index 1 to index 5 with gap of 1
print(arr[1:5:2])# 5 is exclude here

[2 4]


In [16]:
# Return every other element from the entire array

In [18]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])# print 0 index to last index  with step value 2 mean gap of 1

[1 3 5 7]


# Slicing 2D Array's  

In [19]:
# From second element:Slice elements from index 1 to index 4(not include)

In [20]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array
print(arr[1,1:4]) # left handside represent rows and right handside represent columns  
                     # go to one row  and go index from 1:4

[7 8 9]


In [22]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array
print(arr[0:2,2])# from L.H.S 0:2 we take 0 row and 1 row , 2 is exclude  and R.H.S 2 represent second columns

[3 8]


In [23]:
# from both elements,slice index 1 to index 4(not include) this will returrn a 2D array

In [24]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array
print(arr[0:2,1:4]) # l.H.S represent row 0 and 1 row include and R.H.S represent Column 1,2,3 and 4 column is exclude


[[2 3 4]
 [7 8 9]]


#  NumPy Slice as a Reference:(Slice of array is not copy it is reference to original array)

In [26]:
import numpy as np
arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])# 2D array
print("The NumPy array is :")
print(arr)
arr1 = arr[1:,2:]# row 1(se jayega jitni b row hon) onward and column 2(2colum se jayega) onward ,arr1 is now pointing to a subset of arr,
print("The Sliced Numpy array is :")
print(arr1)

The NumPy array is :
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The Sliced Numpy array is :
[[6 7 8]
 [7 6 5]]


In [31]:
import numpy as np
arr=np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])# 2D array
print("The NumPy array is :")
print(arr)
arr1 = arr[1:,2:]# row 1(se jayega jitni b row hon) onward and column 2(2colum se jayega) onward ,arr1 is now pointing to a subset of arr,
print("The Sliced Numpy array is :")
print(arr1)
arr1[0,2]=88 # 0 row and 2 column we updated value as 88
print("Updated NumPy array1 is:")
print(arr1)
print("Updated NumPy array is:")
print(arr)

The NumPy array is :
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The Sliced Numpy array is :
[[6 7 8]
 [7 6 5]]
Updated NumPy array1 is:
[[ 6  7 88]
 [ 7  6  5]]
Updated NumPy array is:
[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


In [34]:
import numpy as np
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])#2D
print("The Numpy array is:")
print(arr1)
print("The shape of Numpy array is ")
print(arr1.shape)

The Numpy array is:
[[ 6  7 88]
 [ 7  6  5]]
The shape of Numpy array is 
(2, 3)


In [35]:
import numpy as np
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])#2D
print("The Numpy array is:")
print(arr)
arr1= arr[2:,:] # row 2 onwords and all columns (2: which print rank2 matrix)
print("The Sliced Numpy Array is :")
print(arr1)
print("The Shape of Numpy array is:")
print(arr1.shape)

The Numpy array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The Sliced Numpy Array is :
[[9 8 7 6 5]]
The Shape of Numpy array is:
(1, 5)


In [36]:
import numpy as np
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[9,8,7,6,5]])#2D
print("The Numpy array is:")
print(arr)
arr1= arr[2,:] # row 2 onwords and all columns (2, which print rank1 matrix)
print("The Sliced Numpy Array is :")
print(arr1)
print("The Shape of Numpy array is:")
print(arr1.shape)

The Numpy array is:
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
The Sliced Numpy Array is :
[9 8 7 6 5]
The Shape of Numpy array is:
(5,)
