In [7]:
# Arithematic operations on arrays

In [1]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
print("Addition of A and B is:")
print(A+B)

Addition of A and B is:
[[ 8 10 12]
 [14 16 18]]


In [2]:
# Array Math is important for vector calculation as well and we can plot graph also

In [3]:
import numpy as np
X=np.array([2,3])
Y=np.array([4,2])
print("Addition of X and Y is :")
print(X+Y) # as like vector addition
 

Addition of X and Y is :
[6 5]


In [4]:
#Using np.add
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
print("Addition of A and B is:")
print(np.add(A,B))

Addition of A and B is:
[[ 8 10 12]
 [14 16 18]]


In [5]:
# Subtraction

In [6]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])# rank 2 matrix
B=np.array([[7,8,9],[10,11,12]])# rank 2 matrix
print("Addition of A and B is:")
print(A-B)

Addition of A and B is:
[[-6 -6 -6]
 [-6 -6 -6]]


In [7]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
print("Addition of A and B is:")
print(np.subtract(A,B))

Addition of A and B is:
[[-6 -6 -6]
 [-6 -6 -6]]


In [8]:
# Multiplication

In [10]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
print("Multiplication of A and B is:")
print(A*B)

Multiplication of A and B is:
[[ 7 16 27]
 [40 55 72]]


In [16]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
print("Multiplication of A and B is:")
print(np.multiply(A,B))

Multiplication of A and B is:
[[ 7 16 27]
 [40 55 72]]


In [17]:
#Division(WE can find BMI(body mass index) of people by division easily)

In [20]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
print("division of A and B is:")#samw as np.divide
print(A/B)

division of A and B is:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [22]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
print("division of A and B is:")#samw as np.divide
print(np.divide(A,B))

division of A and B is:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [11]:
#BMI utilization of arithematic operators
import numpy as np
names=np.array(["Qasim",'Priyanka',"Resham"])# es array k aik aik element k respect me bmi use hoga
heights=np.array([1.5,1.78,1.6])# in meters
weights=np.array([65,46,59])
bmi=weights/heights**2 # calculate BMI=weights/heights(square)
print("The body mass index BMI of Qasim,Priyanka,Resham is:",bmi)
print("overweight:",names[bmi>25])
#overweight:['Qasim']
print("underweight:",names[bmi<18.5])
#underweight:['priyanka']
print("Healthy:",names[(bmi>=18.5) & (bmi<=25)])
#Healthy:['Resham']

The body mass index BMI of Qasim,Priyanka,Resham is: [28.88888889 14.51836889 23.046875  ]
overweight: ['Qasim']
underweight: ['Priyanka']
Healthy: ['Resham']


# Dot Product

In [13]:
import numpy as np
x=np.array([2,3])
y=np.array([4,2])
print("The dot product of x and y is:", np.dot(x,y))

The dot product of x and y is: 14


In [18]:
# rank 2 arrays
import numpy as np
x=np.array([[1,2,3],[4,5,6]]) #2*3 
y=np.array([[7,8],[9,10],[11,12]]) #3*2 #(first matrix column is equal to second matrix row so multiplication possible)
print("The dot product of X and Y is",)
print(np.dot(x,y))

The dot product of X and Y is
[[ 58  64]
 [139 154]]
