In [22]:
# Matrix always 2D and Numpy is nd

In [23]:
import numpy as np
a= np.matrix([[1,2],[4,5]])# consider to be strictly 2 dimension
b=np.matrix([[7,8],[2,3]])# consider to be strictly 2 dimension
print("The matrix a is :")
print(a)
print("The matrix b is:")
print(b)

The matrix a is :
[[1 2]
 [4 5]]
The matrix b is:
[[7 8]
 [2 3]]


In [4]:
# Convert Numpy Array into a matrix using matrix() function(first need to check dimensions)

In [5]:
import numpy as np
a=np.array([[1,2],[4,5]]) # ALWAYS TRY TO CONVERT INTO 2D MATRIX else we get error
b=np.array([[7,8],[2,3]])
c=np.asmatrix(a)
d=np.asmatrix(b)
print("The matrix c is:")
print(c)
print("The matrix d is:")
print(d)

The matrix c is:
[[1 2]
 [4 5]]
The matrix d is:
[[7 8]
 [2 3]]


In [6]:
# first  difference between matrix and numpy array is matrix always 2D and numpy array is nd

In [7]:
import numpy as np

In [9]:
x1=np.array([[1,2],[4,5]])
y1=np.array([[7,8],[2,3]])
print("The product of x1 and y1 is:")#element -by-element multiplication
print(x1*y1)
x2=np.matrix([[1,2],[4,5]])# 2*2 MATRIX
y2=np.matrix([[7,8],[2,3]]) #2*2 MATRIX
print("The product of x2 and y2 is") #dot product;same as np.dot() (Miltply row and columns and + sign in betwewwn because it is dot product)
print(x2*y2)


The product of x1 and y1 is:
[[ 7 16]
 [ 8 15]]
The product of x2 and y2 is
[[11 14]
 [38 47]]


In [11]:
# when we deal numerical data we need cumulative cumsum() function (Cumulative sum hr aik element ka sum hoga)

In [16]:
import numpy as np
A=np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(A)
print("The cumulative cumsum of all element in array is:")
print(A.cumsum()) # 1,1+2,3+3,6+4,.......


The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The cumulative cumsum of all element in array is:
[ 1  3  6 10 15 21 28 36 45]


In [ ]:
# cumulative cumsum columns

In [20]:
import numpy as np
A=np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(A)
print("The commulative cumsum of all the element in each columns of the array is:")
print(A.cumsum(axis=1))# sum of rows

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The commulative cumsum of all the element in each columns of the array is:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [21]:
# cumulative cumsum rows

In [18]:
import numpy as np
A=np.array([(1,2,3),(4,5,6),(7,8,9)])
print("The value of array A is:")
print(A)
print("The commulative cumsum of all the element in each columns of the array is:")
print(A.cumsum(axis=0))# sum of columns

The value of array A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The commulative cumsum of all the element in each columns of the array is:
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
