In [9]:
#list as an input and convert to numpy array(1D array)

In [10]:
import numpy as np
list = [1,2,3,4,5]
arr=np.array(list)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# we can give multiple list as an input 

In [12]:
import numpy as np
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]
arr=np.array([list1,list2,list3])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [13]:
# Take Tuple as an input

In [15]:
import numpy as np
tuple=(1,2,3,4,5)
arr=np.array(tuple)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
# Take Set as an input

In [17]:
import numpy as  np
set={1,2,3,4,5}
arr=np.array(set)
print(arr)
print(type(arr))


{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


In [18]:
# Take Dictionary as input

In [19]:
import numpy as np
dic = {"Name":"Qasim", "Surname":"Abbasi"}
arr=np.array(dic)
print(arr)
print(type(arr))

{'Name': 'Qasim', 'Surname': 'Abbasi'}
<class 'numpy.ndarray'>


# DIMENSIONS FOR NUMPY ARRAY

In [20]:
# Nested(Array)> array have array inside represent as like an element
#dimensions of Numpy are n dimensions
#Code for 0-D are given below(it is a scaler quantity)
#here 10 is scaler quantity

In [23]:
import numpy as np
arr=np.array(10)# 10 is scaler quantity
print(arr)
print(type(arr))

10
<class 'numpy.ndarray'>


In [24]:
# FOr 1-D  Code(it is a 0D elements)

In [26]:
import numpy as np
list=[6,7,8,9,10]
arr=np.array(list)
print(arr)
print(type(arr))

[ 6  7  8  9 10]
<class 'numpy.ndarray'>


In [27]:
# for 2_D Code(It must passess 1D array as an elements)
# use to represent matrix
# second order tensor
# Numpy has a module dedicated to matrix  represent as numpy.mat

In [29]:
import numpy as np
list1=[1,2,3]
list2=[4,5,6]
arr=np.array([list1,list2])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [31]:
# For 3-D (2D array as an elements)
# 3 order tensors
# use 2 square brackets

In [42]:
import numpy as np
list1=[1,2,3]
list2=[4,5,6]
arr=np.array([[list1,list2]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [44]:
# Check No of Dimensions
# use .ndim

In [54]:
import numpy as np
a=np.array(42)
list=[1,2,3,4,5]
b=np.array(list)
list1=[1,2,3]
list2=[4,5,6]
c=np.array([list1,list2])
lista=[1,2,3]
listb=[4,5,6]
d=np.array([[lista,listb]])
print("Dimension of a is",a.ndim)
print("Dimension of b is",b.ndim)
print("Dimension of c is",c.ndim)
print("Dimension of d is",d.ndim)


Dimension of a is 0
Dimension of b is 1
Dimension of c is 2
Dimension of d is 3


In [57]:
# Higher Dimensional Arrays(5-D array)
# firstly convert to 5D and then check the dimensions

In [56]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [59]:
# uptill now results are
#10 Scaler
#[1,2,3] vector
#[[1,2,3]] 2Dmatrix
#[[[1,2,3]]] 3D matrix
#[[[[1,2,3]]]] 4D matrix
#[[[[[1,2,3]]]]] 5D matrix

In [60]:
# Take 2 lists
# for 6D matrix

In [62]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]],ndmin=6)
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[[1 2 3 4]
     [5 6 7 8]]]]]]
number of dimensions: 6
