# Copying by Reference(Assign Numpy array)

In [1]:
import numpy as np
list = [[1,2,3,4],[4,5,6]]# 2D array
array1=np.array(list)
print('The value of array1 is')
print(array1)

The value of array1 is
[list([1, 2, 3, 4]) list([4, 5, 6])]


e:\new folder\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#Value of array1 is assign to value of array 2

In [5]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array is:")
print(array1)
array2=array1 # Assign array1 to array2
print("The value of array 2 is:")
print(array2)

The value of array is:
[[1 2 3]
 [4 5 6]]
The value of array 2 is:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Update the array"s by changing the 0index

In [8]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array is :")
print(array1)
array2=array1 # Assign array1 to array2
print("the value of array2 is:")
print(array2)
array2[0][0]=11 # change  the value of index 0  in an array2 ,also change will occur in array1
print("The updated array2 is:")
print(array2)
print("The updated array1 is:")
print(array1)


The value of array is :
[[1 2 3]
 [4 5 6]]
the value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated array2 is:
[[11  2  3]
 [ 4  5  6]]
The updated array1 is:
[[11  2  3]
 [ 4  5  6]]


In [10]:
#Reshaping Arrays using reshape( )function
# it has property we can change dimension of an array like we can change an array of rank2 to array of rank1

In [12]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array = np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1
print("The value of array2 is:")
print(array2)
#shape is property can change dimension of array
#(1 means that our arrays is of 2D we will change it in 1D 
#and -1 means it's allows to system to choose how manycolumns the output will have conversion of dimension)
array1.shape=1,-1 
print("The updated value of array1 is:")
print(array1)# rank1 array
print("The updated value of array2 is:")
print(array2)#rank1 array

The value of array1 is:
[[11  2  3  4  5  6]]
The value of array2 is:
[[11  2  3  4  5  6]]
The updated value of array1 is:
[[11  2  3  4  5  6]]
The updated value of array2 is:
[[11  2  3  4  5  6]]


# Copying by view(Shallow Copy)

In [14]:
# Another Method to assign an array in Numpy
# use view() function use to create a copy of an array by reference 
# sametime changing shape of original array doesnot affect shape of copy

In [15]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is")
print(array1)
array2=array1.view() # we assign array in different manner
                    #we are performing shallow copy of an array 1 in the form of array2 
print("The value of array2 is:")
print(array2)


The value of array1 is
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]


In [ ]:
# modify a value in array1 and we will see the change in array2 
# in shallow copy view() if we change the shape of array 1 it will not affected array2

In [18]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.view()# creating its shallow copy
print("The value of array2 is:")
print(array2)
array1[0][0]=11 # position element(# Chane here in array 1 and we did update a value of array1(0,0)position=11)
print("The updated value of array is:")
print(array1)
print("The updated value of array2 is:")
print(array2)


The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array is:
[[11  2  3]
 [ 4  5  6]]
The updated value of array2 is:
[[11  2  3]
 [ 4  5  6]]


In [21]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.view()# shallow copy of array1 in the form of array2)
                    #( shallow copy not affect in array2 so array2 same if we update array1
print("The value of array2 is:")
print(array2)
array1.shape=1,-1 

#shape is property can change dimension of array
#(1 means that our arrays is of 2D we will change it in 1D 
#and -1 means it's allows to system to choose how manycolumns the output will have conversion of dimension)
print("The updated value of array is:")
print(array1)
print("The updated value of array2 is:")
print(array2)


The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3]
 [4 5 6]]


# Copying by value(Deep Copying)

In [22]:
import numpy as np
list=[[1,2,3,4],[5,6,7,8]]
array1=np.array(list)
array2=array1.copy() # deep copy of array1 inform of array2 (Copy function do copy)
print("The value of array1 is:")
print(array1)
print("The value of array2 is:")
print(array2)


The value of array1 is:
[[1 2 3 4]
 [5 6 7 8]]
The value of array2 is:
[[1 2 3 4]
 [5 6 7 8]]


In [23]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.copy()# deep copy of array1 inform of array2
print("The value of array2 is:")
print(array2)
array1[0][0]=11 # position element(# Chane here in array 1 and we did update a value of array1(0,0)position=11)
print("The updated value of array is:")
print(array1)
print("The updated value of array2 is:")
print(array2)
#Note array2 is completely different copy of array1 so changes in array1 donot affect array2

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array is:
[[11  2  3]
 [ 4  5  6]]
The updated value of array2 is:
[[1 2 3]
 [4 5 6]]


In [24]:
import numpy as np
list=[[1,2,3],[4,5,6]]
array1=np.array(list)
print("The value of array1 is:")
print(array1)
array2=array1.copy()
print("The value of array2 is:")
print(array2)
array1.shape=1,-1 
#shape is property can change dimension of array
#(1 means that our arrays is of 2D we will change it in 1D 
#and -1 means it's allows to system to choose how manycolumns the output will have conversion of dimension)
print("The updated value of array is:")
print(array1)
print("The updated value of array2 is:")
print(array2)
#Note array2 is completely different copy of array1 so changes in array1 donot affect array2
# no matter if we change shape then also no affect on array2

The value of array1 is:
[[1 2 3]
 [4 5 6]]
The value of array2 is:
[[1 2 3]
 [4 5 6]]
The updated value of array is:
[[1 2 3 4 5 6]]
The updated value of array2 is:
[[1 2 3]
 [4 5 6]]
