In [56]:
# difference between Copy and view

In [57]:
#Copy create a new array(Deep Copy) 
# view is just a reflection of an array(Shallow copy)

In [58]:
#Change the original array and display both arrays

# Copy

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=arr.copy() # for creating copy(Deep Copy) , copy will not update by changing the index
arr[0]=42 # change 0 index with 42
print(arr)
print(arr1)

[42  2  3  4  5]
[1 2 3 4 5]


# View

In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=arr.view() # a shallow copy when update occur in array then also it reflect into a shallow copy
arr[0]=42 # change 0 index with 42
print(arr)
print(arr1)

[42  2  3  4  5]
[42  2  3  4  5]


In [8]:
# Make changes in a view example make a view ,change the view and display both arrays

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=arr.view() # for creating copy , copy will not update by changing the index
arr1[0]=31 # we are updating value of copied array i.e=arr1[0]=31 
#if the change the value of original array it will reflect to copy array
#and print original array and copied array and if 
#we update value of inthe copied array it will reflect into original array
print(arr)
print(arr1)

[31  2  3  4  5]
[31  2  3  4  5]


# Check if Array owns its data

In [10]:
# Copy own the data 
# view doesnot own the data
# use base in numpy that return none if array own the data  otherwise it refer to original object

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy() # Deep copy
y=arr.view() # Shallow copy
print(x.base) # Numpy attribute base
print(y.base) # Numpy attribute base
# if its true copy it will  not return anything and if it's not true it return something

None
[1 2 3 4 5]


# Numpy Array Shapes

In [13]:
# The Shape of an array is no of element in each dimension
# Shape= number of dimension in an array
# Numpy attribute shape which return tuple with each index

# Print shape of a 2D Array

In [15]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]]) # 2D array
print(arr.shape)
# Shape contain as tuple(2,4 which mean we have 2 rows and each row consist of 4 elements


(2, 4)


In [16]:
# we can make a 5D array using ndmin parameter using a vector with 1,2,3,4 and verify last dimension has value 4

In [23]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5) # covert thist list into an array of 5dimension
print(arr)
print('shape of array:',arr.shape)
# 5dimension as like [[[[[]]]]] no of square matrix is 5
# result of this code is [[[[[[1 2 3 4]]]]]] and shape(1,1,1,1,4)
# watch from R.H.S 4 represent 4 element in 5D array result and with 1 reprent first square bracket and so on
# (1,4) =[1,2,3,4] 
#(1,1,1)= representing outer dimension values 
# both will make shape(1,1,1,1,4)


[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [24]:
# by reshapin we can add or remove  dimension we can change number of element in each of dimension

In [25]:
# Convert 1D to 2D

In [30]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])# 1D Array
newarr=arr.reshape(4,3) # Covert 1D to 2D having(4,3) 4 rows and each row will contain of 3 three elements
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
# 1D to 3D

In [34]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])# 1D Array
newarr=arr.reshape(2,3,2) # Covert 1D to 3D having(2,3)  3 rows and each row will contain of 2 two elements and after that
                        #(2,2,3) after 1 comment (2,3) now (2,2,3)it shows it will more convert into 3 rows with two elements
                         #of remaing values of an array
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [35]:
# Can we Reshape array into any shape?
# if we take 8 element in 1D  array into 4 element in 2rows 2D array (possible)
# but we cannot reshape the above statement into 3 elements ,3 rows for a 2D
#because 3x3=9=mxn but we have 8 elements so not possible

In [37]:
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension(will raise an error
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8]) # 8 element available
newarr=arr.reshape(3,3) # 3x3=9 
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [40]:
# Try converting 1D array with 4 elements to a 2D array with 2 elements in each dimension
import numpy as np
arr=np.array([1,2,3,4]) # 4 element available
newarr=arr.reshape(2,2) # 2x2=4 
print(newarr)

[[1 2]
 [3 4]]


# Returns Copy or View

In [42]:
#check if the returned array is a copy or a view
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base) # 2x2=4 
# since we get a complete array in a result so it is a view

[1 2 3 4 5 6 7 8]


# Unknown Dimensions

In [43]:
# when we use reshape we donot what would be dimension we  need to give so we use inplace of dimension use -1 and numpy
#itself Calculated the no of dimension require for you

In [45]:
# Convert 1D array with 8 element to3D array with2x2 elements
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1) # dimension we donot know that's why we use -1 numpy function
print(newarr)
#Note: we cannot pass-1 to more than one dimension

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the Arrays

In [47]:
# converting a multidimensional array into a 1D array(Flattening the Arrays)
#we can use reshape(-1)to do this

In [55]:
#Convert the array into a 1D arraimport 
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr) # Converting 2D array into 1D array
newarr=arr.reshape(-1)
print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
