# Joining Arrays Using Concatenate Functions()

In [8]:
# In SQL we join tables based on a key where we use to fire a query ,In Numpy we join Array on basis of axis
# axis=1,axis=2,axis=3 we pass sequence of arrays which need to join we will apply concatenate() function on them
# along with the axis by which we have to join them if no axis pass it has been taken as 0

In [9]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2)) #concatenate or joining two arrays, here axis is by default 0
print("The Concatenated array is:",arr)

The Concatenated array is: [1 2 3 4 5 6]


In [10]:
# Join two 2-D arrays along rows(axis=1)

In [22]:
import numpy as np
arr1=np.array([[1,2],[3,4]])# 2D array
print(arr1)
arr2=np.array([[5,6],[7,8]])# 2D array
print(arr2)
arr=np.concatenate((arr1,arr2),axis=0) # axis=0(row format) mean 1 row 1 element join with 2 row 1 element and 1 
                                       # row 2 element join with 2 row 2 element
print("The Concatenated array along rows is:",arr)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
The Concatenated array along rows is: [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
import numpy as np
arr1=np.array([[1,2],[3,4]])# 2D array
print(arr1)
arr2=np.array([[5,6],[7,8]])# 2D array
print(arr2)
arr=np.concatenate((arr1,arr2),axis=1) # axis=1 mean 1 row 1 element join with 2 row 1 element and 1 row 2 element join with
                                       # 2 row 2 element
print("The Concatenated array along rows is:",arr)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
The Concatenated array along rows is: [[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions()

In [13]:
# we watch this thing in data structures also,stacking is same as concatenation the only difference is it is done on a 
# new axis ,also if no axis given it will take 0 axis by default

In [15]:
import numpy as np
arr1=np.array([1,2,3])# 1D array
arr2=np.array([4,5,6])# 1D array
arr=np.stack((arr1,arr2)) # stack it will join on a row format when axis=0
print("The stacked array is:")
print(arr)

The stacked array is:
[[1 2 3]
 [4 5 6]]


In [24]:
import numpy as np
arr1=np.array([1,2,3])# 1D array
arr2=np.array([4,5,6])# 1D array
arr=np.stack((arr1,arr2),axis=1)  # stack it will join on a column format when axis=1
print("The stacked array is:")
print(arr)

The stacked array is:
[[1 4]
 [2 5]
 [3 6]]


# Numpy Provide Helper Funct() ,hstack() to stack Along rows

In [28]:
import numpy as np
arr1=np.array([1,2,3])#1D array
arr2=np.array([4,5,6])# 1D array
arr=np.hstack((arr1,arr2)) # here axis is not given so by default it is axis=0 which mean along (row format) stacking
print("The stacked array along rows is:")
print(arr) # elements side by side

The stacked array along rows is:
[1 2 3 4 5 6]


# Numpy Provide Helper Func(),vstack() or vertical stack to stack Along Columns

In [29]:
import numpy as np
arr1=np.array([1,2,3])#1D array
arr2=np.array([4,5,6])# 1D array
arr=np.vstack((arr1,arr2)) # here axis is not given so by default it is axis=0 which mean along (row format) stacking
print("The stacked array along columns is:")
print(arr) # element on top ,botton in form of columns

The stacked array along columns is:
[[1 2 3]
 [4 5 6]]


# Numpy Provide Helper Func():dstack() or depth or height to stack Along Height or Depth

In [30]:
import numpy as np
arr1=np.array([1,2,3])#1D array
arr2=np.array([4,5,6])# 1D array
arr=np.dstack((arr1,arr2)) # here axis is not given so by default it is axis=0 which mean along (row format) stacking
                           # Column element with stack
print("The stacked array along height is:")
print(arr) # element on top ,botton in form of columns

The stacked array along height is:
[[[1 4]
  [2 5]
  [3 6]]]
