In [1]:
list1=[1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [2]:
list2=[1,'Hello',3.14,True,5]
print(list2)

[1, 'Hello', 3.14, True, 5]


# Numpy More Efficient than Python list  deal with multi-dimensional array of same type

In [2]:
import  numpy as np
a1 = np.arange(10)#create a range from 0 to 9
print(a1)#[0 1 2 3 4 5 6 7 8 9]
print(a1.shape)#(10,)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
#specify a step in arange functions

In [4]:
import numpy as np
a2= np.arange(0,10,2)# create a range from 0 to 9,step2
print(a2) #[0 2 4 6 8]
print(a2.shape)

[0 2 4 6 8]
(5,)


In [7]:
import numpy as np
a3 = np.zeros(5)#create an array with all 0s
print(a3) #[0. 0. 0. 0. 0.]
print(a3.shape)#(5,)

[0. 0. 0. 0. 0.]
(5,)


In [8]:
# for creating 2d array (RANK 2) with 2 arguments

In [12]:
import numpy as np
a4 = np.zeros((2,3))# array of rank 2 with all 0s:2 rows and 3 columns
print(a4)
print(a4.shape)#(2,3)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [13]:
# APART FROM ZEROS we want to make a matrix of rank2

In [16]:
import numpy as np
a5 = np.full((2,3),8)# array of rank 2 with all 8s
print(a5)
print(a5.shape)

[[8 8 8]
 [8 8 8]]
(2, 3)


In [17]:
# For Making an Identity Matrix

In [18]:
import numpy as np
a6 = np.eye(4)#4x4 identity matrix
print(a6)
print(a6.shape)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [19]:
# FOR MAKING RANDOM NO ARRAY

In [20]:
import numpy as np
a7 = np.random.random((2,4)) # rank 2 array (2 rows 4 columns) with random values in the half-open interval[0.0 , 1.0)
print(a7)
print(a7.shape)

[[0.59667856 0.46856083 0.73783871 0.81253353]
 [0.35976907 0.28195118 0.28703304 0.78597784]]
(2, 4)


In [21]:
# Create An ARRAY From List