# Searching Arrays

In [1]:
# if any value is present in an array we will get the index where it is present
# use where() function

In [3]:
#Find the indexes where the value is 4
import numpy as np
arr=np.array([1,2,3,4,5,4,4]) # where value 4 is present
x=np.where(arr==4) # search for value 4 by where method and we are giving arr as argument
print(x)

(array([3, 5, 6], dtype=int64),)


In [5]:
# Find the indexes where the values are even
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0) # code for reminder =0
print(x) # will print index value of even no

(array([1, 3, 5, 7], dtype=int64),)


In [6]:
# Find the indexes where the values are odd
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==1) # code for reminder =1 not zero
print(x) # will print index value of odd no

(array([0, 2, 4, 6], dtype=int64),)


# Search Sorted

In [1]:
# it perform binary search in an array
#  suppose we have array of 8 element then binary search look for middle index value  element first and number which we want
# to search it compares it with the middle elements
#) = we have return this value
#) if is less then the value present at the middle then it apply same process toward left of the middle element
#) if is greater then the value present at the middle then it apply same process toward right of the middle element

In [3]:
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7) # searchsorted() first internal sorted will be done then it serach for element 7 
                        # 7 is place on index 1 also by sort it is place at index 1
print(x)# it will print index which is 1

1


# Search from the left Side

In [4]:
# The previous Code is the example of search from the left side
# by default it will search from the left side but we can start it from the right side as well

# Search from the Right Side

In [6]:
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right') # bydefault it was left but we want to ge index value from the right 
print(x)# index position from the right

2


# Multi values

In [7]:
# to search more than one value we can use the array with the specified value

In [9]:
# find the indexes where the values 2,4 and 6 should be inserted
# we are inserted element one by one
import numpy as np
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6]) # 2,4,6 this element need to insert, 2 will be place on 1 index, if we talk about 4 
                                                    # it index should be 2 after 1 and 3 ,if we talk about 6,it will place
                                                    # after 5 so index would be 3 
print(x) # it will print the index position  element 2,4,6 which were inserted to the array

[1 2 3]


# Numpy filter array

In [10]:
# we want some element from existing array and we need to create a new array this is Called filtering
# in NumPy  filtering array can be done with the help of the boolean index listing(True or False) Corresponding to the
 #indices to the array,if the value at the index is true i.e it is present and value of indices is true we will say element
    # contain in the filter array and if is false then element is excluded it is not present

In [12]:
# create an array from the element from the elements  on index 0 and 2
import numpy as np
arr=np.array([41,42,43,44]) # we need  array from 0 index and index 2 so at both index it is True else False
x=[True,False,True,False] # boolean list
newarr=arr[x] # True thing will exist that are filter arrays and false element will not print which will exclude
print(newarr)

[41 43]


# Creating the Filter Array

In [13]:
# we can use some condition instead of True False we did use previously

In [14]:
# create a filter array that will return only value higher than 42
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=[] # create empty list , we are filling up values here by boolean index values
for element in arr: # element is variable present in array(arr)
    if element> 42: # if its true we will append it position in empty list
        filter_arr.append(True)
    else: # if it not greater than 42 so we will append false
        filter_arr.append(False)
newarr=arr[filter_arr] # the position of filter_arr into an array arr will be assign to newarr
print(filter_arr)
print(newarr) # 43,44

[False, False, True, True]
[43 44]


In [19]:
# For an even number
import numpy as np
arr=np.array([1,2,3,4,5,6,7]) # 7 elements
filter_arr=[]
for element in arr: # element is variable present in array(arr)
    if element% 2==0:
        filter_arr.append(True)
    else: 
        filter_arr.append(False)
newarr=arr[filter_arr] # the position of filter_arr into an array arr will be assign to newarr
print(filter_arr)
print(newarr) # 43,44

[False, True, False, True, False, True, False]
[2 4 6]


# Creating Filter Directly From Array

In [20]:
# we can use filter directory from an array because it is getting complicated we are using for loops also
# we are using some conditions also so we have to use an easy method directly

In [21]:
import numpy as np
arr=np.array([41,42,43,44])
filter_arr=arr>42 # it will use true or false according to the input
newarr=arr[filter_arr]  # the position of filter_arr into an array arr will be assign to newarr
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [22]:
# Create a filter array that will return only even elements from the original array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
filter_arr=arr%2==0 # it will use true or false according to the input ,Check the condition
newarr=arr[filter_arr]  # the position of filter_arr into an array arr will be assign to newarr
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
