# NumPy Array Reshape

In [1]:
# We can reshape an array to another dimension using the reshape() function

In [10]:
import numpy as np
list=[1,2,3,4,5]
arr=np.array(list)
print("The NumPy array is:",arr)
print(arr.shape)#Rank1
arr1=arr.reshape(1,-1)#Rank 2(1 represent we want to convert it to rank2 with 1 row )(-1 represent letting the system itself decide how many column will be after reshape)
print("The reshape NumPy array is:",arr1)
print(arr1.shape)
arr2 = arr1.reshape(1,1,-1)# when we try to add one more rank 3D Matrix
print(arr2)
print(arr2.shape)
arr3=arr1.reshape(1,1,1,-1)# when we try to add one more rank 4D Matrix
print(arr3)
print(arr3.shape)


The NumPy array is: [1 2 3 4 5]
(5,)
The reshape NumPy array is: [[1 2 3 4 5]]
(1, 5)
[[[1 2 3 4 5]]]
(1, 1, 5)
[[[[1 2 3 4 5]]]]
(1, 1, 1, 5)


In [11]:
# Same Code but we are not leaving on system to decide how many columns After reshaping

In [14]:
import numpy as np
list=[1,2,3,4,5]
arr=np.array(list)
print("The NumPy array is:",arr)
print(arr.shape)#Rank1
arr1=arr.reshape(1,5)#Rank 2(1 represent we want to convert it to rank2 with 1 row )(only Change here)
print("The reshape NumPy array is:",arr1)
print(arr1.shape)
arr2 = arr1.reshape(1,1,-1)# when we try to add one more rank 3D Matrix
print(arr2)
print(arr2.shape)
arr3=arr1.reshape(1,1,1,-1)# when we try to add one more rank 4D Matrix
print(arr3)
print(arr3.shape)


The NumPy array is: [1 2 3 4 5]
(5,)
The reshape NumPy array is: [[1 2 3 4 5]]
(1, 5)
[[[1 2 3 4 5]]]
(1, 1, 5)
[[[[1 2 3 4 5]]]]
(1, 1, 1, 5)


In [15]:
#lets Consider another code to reshape "arr1"(which is rank 2 array) to rank1

In [19]:
import numpy as np
list=[1,2,3,4,5]
arr1=np.array([list])
print("The Numpy array is:",arr1)#rank 2 matrix
arr=arr1.reshape(-1,)#(we convert rank 2 matrix to rank 1 matrix with the help of -1 arguments )
print("The reshape NumPy is:",arr)


The Numpy array is: [[1 2 3 4 5]]
The reshape NumPy is: [1 2 3 4 5]


In [ ]:
#Instead of reshape function

In [20]:
import numpy as np
list=[1,2,3,4,5]
arr1=np.array([list])
print("The Numpy array is:",arr1)#rank 2 matrix
arr=arr1.flatten()#(we convert rank 2 matrix to rank 1 matrix with the help of flatten function )
print("The reshape NumPy is:",arr)


The Numpy array is: [[1 2 3 4 5]]
The reshape NumPy is: [1 2 3 4 5]


In [22]:
import numpy as np
list=[1,2,3,4,5]
arr1=np.array([list])
print("The Numpy array is:",arr1)#rank 2 matrix
arr=arr1.ravel() #(we convert rank 2 matrix to rank 1 matrix with the help of ravel function )
print("The reshape NumPy is:",arr)


The Numpy array is: [[1 2 3 4 5]]
The reshape NumPy is: [1 2 3 4 5]


In [23]:
# Data type of python are 5
#string,integers,float,boolean,complex
#Data types in NumPy are 11 represent by i,b,u,f,c,m,M,O,S,U,V

# Data Types in NumPy

In [24]:
#Get the data type of an array object

In [26]:
import numpy as np
arr=np.array([1,2,3,4,])#list have integeres so dtype will be integers
print("The data type of arr is:" ,arr.dtype)

The data type of arr is: int32


In [27]:
# Get the data type of an array consisting strings

In [29]:
import numpy as np
arr=np.array(['apple','banana','cherry'])
print("the data type of arr is:", arr.dtype) # U is unicode strings


the data type of arr is: <U6


# Creating Array with a Defined Data Type

In [33]:
# create an array with data type string
import numpy as np
arr=np.array([1,2,3,4],dtype='S')# integers convert into strings
print("The value of arr is:",arr)
print("The data type of arr is:",arr.dtype)

The value of arr is: [b'1' b'2' b'3' b'4']
The data type of arr is: |S1


In [34]:
# create an array with data type 4 bytes integers

In [37]:
import numpy as np
arr=np.array([1,2,3,4],dtype="i4")# all elements in list willbe of 8 bytes so total is int32
print("The value of arr:", arr)
print("The data type of arr is",arr.dtype)

The value of arr: [1 2 3 4]
The data type of arr is int32


In [42]:
import numpy as np
arr=np.array([1,2,3,4],dtype="i8") # all elements in list willbe of 16 bytes so total is int32
print("The value of arr:", arr)
print("The data type of arr is",arr.dtype)

The value of arr: [1 2 3 4]
The data type of arr is int64


# Value Error

In [43]:
import numpy as np
arr=np.array(['a','2','3'],dtype='i')# string can not convert into integer
print("The value of arr is:",arr)

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing arrays

In [44]:
# we can make a copy of array with astype( method)

In [46]:
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')# change float to integers
print("The value of new arr is:",newarr)
print("The data type of newarr is:",newarr.dtype)

The value of new arr is: [1 2 3]
The data type of newarr is: int32


In [47]:
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype(int)# change float to integers
print("The value of new arr is:",newarr)
print("The data type of newarr is:",newarr.dtype)

The value of new arr is: [1 2 3]
The data type of newarr is: int32


In [48]:
# Change data type from integer to Boolean

In [51]:
import numpy as np
arr=np.array([1,0,3])#0 represent by false
newarr=arr.astype(bool)
print("The value of newarr is:",newarr)
print("The data type of newarr is:",newarr.dtype)

The value of newarr is: [ True False  True]
The data type of newarr is: bool


In [52]:
import numpy as np
arr=np.array([1.5,3.4,3.8])#0 represent by false
newarr=arr.astype(bool)
print("The value of newarr is:",newarr)
print("The data type of newarr is:",newarr.dtype)

The value of newarr is: [ True  True  True]
The data type of newarr is: bool
